# Generated by Django 2.2.6 on 2019-11-04 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_en', models.CharField(blank=True, max_length=50)),
                ('audience', models.IntegerField(default=0)),
                ('open_date', models.DateField(default=django.utils.timezone.now)),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('watch_grade', models.CharField(blank=True, max_length=50)),
                ('score', models.FloatField(default=0)),
                ('poster_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
